before:
  hooks:
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - freebsd
  - windows

archive:
  replacements:
    darwin: macos
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - 'README'
