// Code generated by mockery v1.0.0. DO NOT EDIT.

package license

import mock "github.com/stretchr/testify/mock"

// MockStatusListener is an autogenerated mock type for the StatusListener type
type MockStatusListener struct {
	mock.Mock
}

// UpdateStatus provides a mock function with given fields: t, msg
func (_m *MockStatusListener) UpdateStatus(t StatusType, msg string) {
	_m.Called(t, msg)
}
